USE [master]
GO

/****** Object:  Database [ShoppingCartDB]    Script Date: 4/24/2025 5:19:34 PM ******/
CREATE DATABASE [ShoppingCartDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ShoppingCartDB', FILENAME = N'Q:\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ShoppingCartDB.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ShoppingCartDB_log', FILENAME = N'Q:\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ShoppingCartDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ShoppingCartDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ShoppingCartDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ShoppingCartDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ShoppingCartDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ShoppingCartDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ShoppingCartDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [ShoppingCartDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ShoppingCartDB] SET  MULTI_USER 
GO

ALTER DATABASE [ShoppingCartDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ShoppingCartDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ShoppingCartDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ShoppingCartDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ShoppingCartDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ShoppingCartDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ShoppingCartDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [ShoppingCartDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ShoppingCartDB] SET  READ_WRITE 
GO

